name: CI build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.14.1
        platform:
          - gcc_64
          - android
          - wasm_32
          - msvc2017_64
          - msvc2017
          - winrt_x64_msvc2017
          - winrt_x86_msvc2017
          #- winrt_armv7_msvc2017  # Fails with MSVC2017 in VS2019
          - mingw73_64
          - mingw73_32
          - clang_64
          - ios
        config:
          - "CONFIG+=cryptopp_omp"  # linux only, ignored on other platforms
          - "CONFIG+=static"
        pro-file:
          - cryptopp.pro
          - cryptopp-helper.pro
          - cryptopp-basic.pro

        include:
          - platform: gcc_64
            os: ubuntu-latest
          - platform: android
            os: ubuntu-latest
          - platform: wasm_32
            os: ubuntu-latest
            emsdk: sdk-fastcomp-1.38.27-64bit
          - platform: msvc2017_64
            os: windows-latest
          - platform: msvc2017
            os: windows-latest
          - platform: winrt_x64_msvc2017
            os: windows-latest
          - platform: winrt_x86_msvc2017
            os: windows-latest
          - platform: winrt_armv7_msvc2017
            os: windows-latest
          - platform: mingw73_64
            os: windows-latest
          - platform: mingw73_32
            os: windows-latest
          - platform: clang_64
            os: macos-latest
          - platform: ios
            os: macos-latest

          - pro-file: cryptopp.pro
            testpro: default
          - pro-file: cryptopp-helper.pro
            testpro: helper
          - pro-file: cryptopp-basic.pro
            testpro: basic

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - name: actions/cache emsdk
        uses: actions/cache@v1
        if: matrix.platform == 'wasm_32'
        with:
          path: emsdk-cache
          key: ${{runner.os}}-emsdk-${{matrix.emsdk}}
      - uses: mymindstorm/setup-emsdk@v3
        if: matrix.platform == 'wasm_32'
        with:
          version: ${{matrix.emsdk}}
          actions-cache-folder: emsdk-cache
      - name: actions/cache qt
        uses: actions/cache@v1
        id: cache-qt
        with:
          path: qt/${{matrix.version}}/${{matrix.platform}}
          key: qt-${{matrix.version}}-${{matrix.platform}}
      - uses: Skycoder42/action-setup-qt@master
        id: qt
        with:
          version: ${{matrix.version}}
          platform: ${{matrix.platform}}
          cachedir: qt/${{matrix.version}}/${{matrix.platform}}
      - name: prepare build
        if: matrix.pro-file == 'cryptopp-helper.pro'
        shell: bash
        run: mv test/.qmake.conf ./
      - run: mkdir build
      - name: qmake
        run: qmake ${{matrix.config}} ../${{matrix.pro-file}}
        working-directory: build
      - name: make
        run: ${{steps.qt.outputs.make}}
        working-directory: build
      - run: mkdir build/test
      - name: qmake test
        run: qmake "TEST_PRI_PATH=${{matrix.testpro}}.pri" ../../test/test.pro
        working-directory: build/test
      - name: make test
        run: ${{steps.qt.outputs.make}}
        working-directory: build/test
